meido:
  jabber_id:
  password:
  host: 'talk.google.com'
  status_msg: 'おはよう、ご主人様！'

twitter:
  consumer_key:
  consumer_secret:
  username:
  password:

google:
  consumer_key:
  consumer_secret:
  access_key:
  domain:
